type = "checkout_ui_extension"
name = "checkout-ui-extension"

extension_points = [
  'Checkout::Dynamic::Render',
  'Checkout::Contact::RenderAfter',
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::ShippingMethods::RenderAfter',
  'Checkout::CartLineDetails::RenderAfter'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

[capabilities]
api_access = true

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
